name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    env:
      name: steeven sayago

    steps:
      - name: hola mundo
        run: echo "Hola mundo  de ${{ env.name }}"

  second_job:
    # if: false
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: hola mundo
        # if: false
        run: echo "Hola mundo en un segundo jobs"
