name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  first_job:
    name: Primer trabajo asignado
    runs-on: ubuntu-latest

    outputs:
      salida: hola sali ya

    env:
      name: steeven sayago

    steps:
      - name: generar archivo
        run: echo "Hola mundo  de ${{ env.name }}">>test.log

      - name: subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo test
          path: test.log
