name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  first_job:
    name: Primer trabajo asignado
    runs-on: ubuntu-latest

    outputs:
      salida: hola sali ya

    env:
      name: steeven sayago

    steps:
      - name: hola mundo
        run: echo "Hola mundo  de ${{ env.name }}"

  second_job:
    # if: false
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: hola mundo working dir
        # if: false
        run: ls -al

      - name: action
        uses: actions/checkout@v4

      - name: def variable
        id: def_variable
        run: echo "my_variable= hola mundo variable">> $GITHUB_OUTPUT

      - name: msj
        run: echo "${{ steps.def_variable.outputs.my_variable }}"
